package com.listo.DynamoDBToDo.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTyped;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapperFieldModel.DynamoDBAttributeType;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;

@Data
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "Todo")
public class Todo {

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute(attributeName = "title")
    private String title;

    @DynamoDBAttribute(attributeName = "description")
    private String description;

    @DynamoDBAttribute(attributeName = "completed")
    @DynamoDBTyped(DynamoDBAttributeType.BOOL)
    private boolean completed;

//    @DynamoDBAttribute(attributeName = "createdAt")
//    @DynamoDBTyped(DynamoDBAttributeType.S)
//    private LocalDateTime createdAt;
//
//    @DynamoDBAttribute(attributeName = "updatedAt")
//    @DynamoDBTyped(DynamoDBAttributeType.S)
//    private LocalDateTime updatedAt;
}